"""add_seller_indexes

Revision ID: 0d5ad283564a
Revises: 8329eb4daaeb
Create Date: 2026-02-04 00:50:10.349342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d5ad283564a'
down_revision: Union[str, Sequence[str], None] = '8329eb4daaeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_seller_category'), 'seller', ['category'], unique=False)
    op.create_index(op.f('ix_seller_email'), 'seller', ['email'], unique=False)
    op.create_index(op.f('ix_seller_name'), 'seller', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seller_name'), table_name='seller')
    op.drop_index(op.f('ix_seller_email'), table_name='seller')
    op.drop_index(op.f('ix_seller_category'), table_name='seller')
    # ### end Alembic commands ###
