"""add_phone_auth

Revision ID: 4954fb1b6185
Revises: a1b2c3d4e5f6
Create Date: 2026-02-02 00:02:40.935426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4954fb1b6185'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_login_code', sa.Column('phone_number', sa.String(), nullable=True))
    op.alter_column('auth_login_code', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_auth_login_code_phone_number'), 'auth_login_code', ['phone_number'], unique=False)
    op.add_column('auth_session', sa.Column('phone_number', sa.String(), nullable=True))
    op.alter_column('auth_session', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_auth_session_phone_number'), 'auth_session', ['phone_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_session_phone_number'), table_name='auth_session')
    op.alter_column('auth_session', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('auth_session', 'phone_number')
    op.drop_index(op.f('ix_auth_login_code_phone_number'), table_name='auth_login_code')
    op.alter_column('auth_login_code', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('auth_login_code', 'phone_number')
    # ### end Alembic commands ###
