"""add_choice_factors_to_row

Revision ID: 6fed377b628a
Revises: ddc57c9ac3c9
Create Date: 2026-01-18 18:22:57.283423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6fed377b628a'
down_revision: Union[str, Sequence[str], None] = 'ddc57c9ac3c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('row', sa.Column('choice_factors', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('row', sa.Column('choice_answers', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('row', 'choice_answers')
    op.drop_column('row', 'choice_factors')
    # ### end Alembic commands ###
