"""add_seller_fields

Revision ID: 8329eb4daaeb
Revises: 4954fb1b6185
Create Date: 2026-02-03 23:52:49.383189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8329eb4daaeb'
down_revision: Union[str, Sequence[str], None] = '4954fb1b6185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seller', sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('seller', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('seller', sa.Column('contact_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('seller', sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seller', 'phone')
    op.drop_column('seller', 'contact_name')
    op.drop_column('seller', 'category')
    op.drop_column('seller', 'image_url')
    # ### end Alembic commands ###
