"""add_search_architecture_v2_fields

Revision ID: a6b8420ffc92
Revises: 923cedba39d9
Create Date: 2026-01-29 23:24:53.101278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a6b8420ffc92'
down_revision: Union[str, Sequence[str], None] = '923cedba39d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Made idempotent — columns may already exist from init_db
    op.execute("ALTER TABLE bid ADD COLUMN IF NOT EXISTS canonical_url VARCHAR")
    op.execute("ALTER TABLE bid ADD COLUMN IF NOT EXISTS source_payload VARCHAR")
    op.execute("ALTER TABLE bid ADD COLUMN IF NOT EXISTS search_intent_version VARCHAR")
    op.execute("ALTER TABLE bid ADD COLUMN IF NOT EXISTS normalized_at TIMESTAMP")
    op.execute("ALTER TABLE row ADD COLUMN IF NOT EXISTS search_intent VARCHAR")
    op.execute("ALTER TABLE row ADD COLUMN IF NOT EXISTS provider_query_map VARCHAR")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('row', 'provider_query_map')
    op.drop_column('row', 'search_intent')
    op.drop_column('bid', 'normalized_at')
    op.drop_column('bid', 'search_intent_version')
    op.drop_column('bid', 'source_payload')
    op.drop_column('bid', 'canonical_url')
    # ### end Alembic commands ###
