"""add_search_architecture_v2_fields

Revision ID: a6b8420ffc92
Revises: 923cedba39d9
Create Date: 2026-01-29 23:24:53.101278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a6b8420ffc92'
down_revision: Union[str, Sequence[str], None] = '923cedba39d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bid', sa.Column('canonical_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('bid', sa.Column('source_payload', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('bid', sa.Column('search_intent_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('bid', sa.Column('normalized_at', sa.DateTime(), nullable=True))
    op.add_column('row', sa.Column('search_intent', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('row', sa.Column('provider_query_map', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('row', 'provider_query_map')
    op.drop_column('row', 'search_intent')
    op.drop_column('bid', 'normalized_at')
    op.drop_column('bid', 'search_intent_version')
    op.drop_column('bid', 'source_payload')
    op.drop_column('bid', 'canonical_url')
    # ### end Alembic commands ###
