"""add is_service and service_category to row

Revision ID: ae820ac5eef6
Revises: 0d5ad283564a
Create Date: 2026-02-04 10:22:09.380875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae820ac5eef6'
down_revision: Union[str, Sequence[str], None] = '0d5ad283564a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add with default for existing rows, then make non-nullable
    op.add_column('row', sa.Column('is_service', sa.Boolean(), nullable=True, server_default='false'))
    op.execute("UPDATE row SET is_service = false WHERE is_service IS NULL")
    op.alter_column('row', 'is_service', nullable=False)
    op.add_column('row', sa.Column('service_category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('row', 'service_category')
    op.drop_column('row', 'is_service')
    # ### end Alembic commands ###
