"""add_clickout_event_table

Revision ID: ddc57c9ac3c9
Revises: 
Create Date: 2026-01-18 18:15:20.558971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ddc57c9ac3c9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clickout_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('row_id', sa.Integer(), nullable=True),
    sa.Column('offer_index', sa.Integer(), nullable=False),
    sa.Column('canonical_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('final_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('merchant_domain', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('handler_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('affiliate_tag', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clickout_event_merchant_domain'), 'clickout_event', ['merchant_domain'], unique=False)
    op.create_index(op.f('ix_clickout_event_row_id'), 'clickout_event', ['row_id'], unique=False)
    op.create_index(op.f('ix_clickout_event_user_id'), 'clickout_event', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clickout_event_user_id'), table_name='clickout_event')
    op.drop_index(op.f('ix_clickout_event_row_id'), table_name='clickout_event')
    op.drop_index(op.f('ix_clickout_event_merchant_domain'), table_name='clickout_event')
    op.drop_table('clickout_event')
    # ### end Alembic commands ###
