"""add_project_model

Revision ID: e01f187cef03
Revises: add_clerk_fields
Create Date: 2026-01-23 13:41:45.690440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e01f187cef03'
down_revision: Union[str, Sequence[str], None] = 'add_clerk_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('row', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_row_project_id'), 'row', ['project_id'], unique=False)
    op.create_foreign_key(None, 'row', 'project', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'row', type_='foreignkey')
    op.drop_index(op.f('ix_row_project_id'), table_name='row')
    op.drop_column('row', 'project_id')
    # ### end Alembic commands ###
