export default function TermsPage() {
  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
      <h1 className="text-4xl font-bold text-gray-900 mb-2">Terms of Service</h1>
      <p className="text-sm text-gray-500 mb-12">Last updated: February 2026</p>

      <div className="prose prose-gray max-w-none space-y-8">
        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">1. Introduction Platform</h2>
          <p className="text-gray-600 leading-relaxed">
            BuyAnything is an introduction platform. We connect buyers with sellers — both through affiliate links to major retailers and through direct introductions to vendors in our network. We do not sell products or services ourselves, do not hold inventory, and do not process payments between buyers and vendors (except through affiliate networks where applicable).
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">2. No Warranties on Vendor Performance</h2>
          <p className="text-gray-600 leading-relaxed">
            When we connect you with a vendor, we facilitate the introduction only. We do not guarantee the quality, pricing, availability, or timeliness of any vendor&apos;s products or services. Any transaction between you and a vendor is between you and that vendor directly. We encourage you to verify vendor credentials and terms before committing to any purchase.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">3. Affiliate Links</h2>
          <p className="text-gray-600 leading-relaxed">
            Product links on BuyAnything may be affiliate links. When you purchase through these links, we may earn a commission at no additional cost to you. Prices are set by the retailer, not by BuyAnything. We do not guarantee the accuracy of prices displayed on our platform — prices are fetched from retailer APIs and may change at any time.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">4. Search Results</h2>
          <p className="text-gray-600 leading-relaxed">
            Search results are generated by querying multiple sources simultaneously and ranking results by relevance to your request. Results are not influenced by payments from vendors or retailers. Ranking is based on algorithmic scoring that considers relevance, price fit, quality signals, and source diversity.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">5. Account Usage</h2>
          <p className="text-gray-600 leading-relaxed">
            You may use BuyAnything&apos;s public search without an account. Creating an account gives you access to the workspace, saved searches, vendor outreach, and project management features. You are responsible for maintaining the security of your account credentials.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">6. Acceptable Use</h2>
          <p className="text-gray-600 leading-relaxed">
            You may not use BuyAnything to: scrape or bulk-download search results, submit automated queries exceeding rate limits, impersonate others in vendor communications, or use the platform for any illegal purpose. We reserve the right to restrict access for violations of these terms.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">7. Changes to Terms</h2>
          <p className="text-gray-600 leading-relaxed">
            We may update these terms from time to time. Continued use of the platform after changes constitutes acceptance of the revised terms.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">8. Contact</h2>
          <p className="text-gray-600 leading-relaxed">
            For questions about these terms, contact us at <a href="mailto:legal@buyanything.ai" className="text-blue-600 hover:underline">legal@buyanything.ai</a>.
          </p>
        </section>
      </div>
    </div>
  );
}
