import asyncio
import csv
import json
import logging
import os
import re
import sys
from datetime import datetime
from pathlib import Path
from typing import Optional, Dict, Any, List

import httpx

sys.path.insert(0, str(Path(__file__).parent.parent))

from dotenv import load_dotenv
load_dotenv(Path(__file__).parent.parent / ".env")

from sqlalchemy import text
from sqlalchemy.orm import sessionmaker
from sqlmodel.ext.asyncio.session import AsyncSession
from database import engine

# Setup logging to be clean and simple
logging.basicConfig(level=logging.INFO, format="%(message)s")
logger = logging.getLogger(__name__)
# Suppress noisy HTTP logs from httpx
logging.getLogger("httpx").setLevel(logging.WARNING)

OLLAMA_API_URL = os.getenv("OLLAMA_API_URL", "http://127.0.0.1:11434/api/chat")
OLLAMA_MODEL = os.getenv("OLLAMA_MODEL", "gpt-oss:20b")
OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")
EMBEDDING_MODEL = os.getenv("EMBEDDING_MODEL", "openai/text-embedding-3-small")
SERPAPI_API_KEY = os.getenv("SERPAPI_API_KEY")

CSV_INPUT = Path(__file__).parent.parent.parent.parent / "docs/sales/Pop_Targets_V2_Top100.csv"
CSV_OUTPUT = Path(__file__).parent.parent.parent.parent / "docs/sales/Pop_Targets_V2_Top100_Enriched.csv"

LLM_SEM = asyncio.Semaphore(3)

EXTRACT_PROMPT = """You are an expert B2B lead generator and data enricher.
Research the CPG brand: "{brand}".

I have searched the web for you. Here is the context about the brand and people working there:
{search_context}

Your goal is to extract their company details and specific key personnel from the provided text.
Find the names, titles, and (if available) emails or LinkedIn URLs of people currently working at {brand} with any of these titles (or similar): {buyer_titles}.

You must output ONLY valid JSON format. Do NOT use tool calls. Do not include your thinking.
Fill in ALL the fields with the information you found in the context. Do not leave them empty if the information is available.
Required JSON Structure:
{{
    "website": "https://...",
    "tagline": "Short 1-sentence tagline",
    "description": "Detailed description of the company and their main products.",
    "seo_summary": "High-density 2-3 sentence summary of their core offerings.",
    "services_list": ["Product 1", "Product 2"],
    "contacts": [
        {{
            "name": "Jane Doe",
            "title": "VP of Growth",
            "email_or_linkedin": "jane@example.com or https://linkedin.com/in/..."
        }}
    ]
}}
"""

REPAIR_PROMPT = """You are a JSON repair and data extraction bot. 
The following text was generated by a weaker model trying to extract company info from search results.
It either produced invalid JSON, or it missed the details and returned empty fields.

Your job is to fix it. Use the provided Search Context to properly fill out the JSON.
Return ONLY valid JSON matching this schema. Do not include markdown fences.

Schema:
{{
    "website": "string",
    "tagline": "string",
    "description": "string",
    "seo_summary": "string",
    "services_list": ["string"],
    "contacts": [
        {{"name": "string", "title": "string", "email_or_linkedin": "string"}}
    ]
}}

Weak Model Output:
{raw_text}

Search Context:
{context}
"""

def perform_search(query: str) -> str:
    if not SERPAPI_API_KEY:
        return ""
    try:
        resp = httpx.get(
            "https://serpapi.com/search",
            params={
                "api_key": SERPAPI_API_KEY,
                "q": query,
                "engine": "google",
                "num": 4
            },
            timeout=15
        )
        resp.raise_for_status()
        data = resp.json()
        context = []
        for r in data.get("organic_results", []):
            context.append(f"Title: {r.get('title')}\nURL: {r.get('link')}\nSnippet: {r.get('snippet')}\n")
        return "\n".join(context)
    except Exception as e:
        return ""

async def repair_json_with_openrouter(raw_text: str, context: str) -> Optional[Dict]:
    prompt = REPAIR_PROMPT.format(raw_text=raw_text, context=context)
    try:
        async with httpx.AsyncClient(timeout=60) as client:
            resp = await client.post(
                "https://openrouter.ai/api/v1/chat/completions",
                headers={
                    "Authorization": f"Bearer {OPENROUTER_API_KEY}",
                    "Content-Type": "application/json",
                },
                json={
                    "model": "google/gemini-3-flash-preview",
                    "messages": [{"role": "user", "content": prompt}],
                    "temperature": 0.1
                }
            )
            resp.raise_for_status()
            content = resp.json()["choices"][0]["message"]["content"]
            content = content.strip()
            if content.startswith("```"):
                content = re.sub(r"^```(?:json)?\n?", "", content)
                content = re.sub(r"\n?```$", "", content)
            return json.loads(content)
    except Exception as e:
        return None

async def llm_research_brand(brand: str, buyer_titles: str) -> Optional[Dict[str, Any]]:
    company_search = perform_search(f'"{brand}" CPG brand products')
    people_search = perform_search(f'"{brand}" ("VP of Growth" OR "Shopper Marketing" OR "VP Ecommerce") site:linkedin.com/in')
    
    context = f"--- COMPANY INFO ---\n{company_search}\n\n--- KEY PERSONNEL ---\n{people_search}"
    prompt = EXTRACT_PROMPT.format(brand=brand, buyer_titles=buyer_titles, search_context=context)
    
    raw_content = ""
    try:
        async with LLM_SEM:
            async with httpx.AsyncClient(timeout=300) as client:
                resp = await client.post(
                    OLLAMA_API_URL,
                    json={
                        "model": OLLAMA_MODEL,
                        "messages": [{"role": "user", "content": prompt}],
                        "stream": False,
                        "options": {
                            "temperature": 0.1,
                            "num_predict": 1000
                        }
                    },
                )
                resp.raise_for_status()
                msg = resp.json().get("message", {})
                raw_content = msg.get("content", "")
    except Exception as e:
        return None

    needs_repair = False
    parsed = None
    try:
        cleaned = raw_content.strip()
        if cleaned.startswith("```"):
            cleaned = re.sub(r"^```(?:json)?\n?", "", cleaned)
            cleaned = re.sub(r"\n?```$", "", cleaned)
        parsed = json.loads(cleaned)
        
        if not parsed.get("website") and not parsed.get("tagline") and not parsed.get("contacts"):
            needs_repair = True
    except json.JSONDecodeError:
        needs_repair = True
        
    if needs_repair:
        parsed = await repair_json_with_openrouter(raw_content, context)
        
    return parsed

async def generate_embedding(text_to_embed: str) -> Optional[List[float]]:
    if not OPENROUTER_API_KEY:
        return None
    try:
        async with httpx.AsyncClient(timeout=30) as client:
            resp = await client.post(
                "https://openrouter.ai/api/v1/embeddings",
                headers={
                    "Authorization": f"Bearer {OPENROUTER_API_KEY}",
                    "Content-Type": "application/json",
                },
                json={"model": EMBEDDING_MODEL, "input": text_to_embed},
            )
            resp.raise_for_status()
            data = resp.json()
            return data["data"][0]["embedding"]
    except Exception as e:
        return None

def _fallback_slug(name: str) -> str:
    base = (name or "brand").lower().strip()
    base = re.sub(r"[^a-z0-9\s-]", "", base)
    return re.sub(r"[\s_-]+", "-", base).strip("-")

async def process_brand(session: AsyncSession, row: Dict[str, str]) -> Dict[str, str]:
    brand = row["Brand"]
    buyer_titles = row.get("Suggested buyer titles", "VP of Growth, Director of Shopper Marketing")
    
    extracted = await llm_research_brand(brand, buyer_titles)
    if not extracted:
        logger.error(f"   ❌ Failed to extract data for {brand}")
        return row
    
    website = extracted.get("website")
    tagline = extracted.get("tagline")
    description = extracted.get("description")
    seo_summary = extracted.get("seo_summary")
    contacts = extracted.get("contacts", [])
    
    logger.info(f"   ✓ Extracted: {website}")
    logger.info(f"   ✓ Tagline: {tagline}")
    if contacts:
        logger.info(f"   ✓ Found {len(contacts)} contacts:")
        for c in contacts:
            name = c.get("name", "")
            title = c.get("title", "")
            link = c.get("email_or_linkedin", "")
            logger.info(f"      - {name} ({title}) -> {link}")
    else:
        logger.info(f"   ⚠️  No contacts found.")
        
    contact_names = [c.get("name", "") for c in contacts]
    contact_titles = [c.get("title", "") for c in contacts]
    contact_links = [c.get("email_or_linkedin", "") for c in contacts]
        
    row["Website"] = website
    row["Contact Names"] = " | ".join(contact_names)
    row["Contact Titles"] = " | ".join(contact_titles)
    row["Contact Links"] = " | ".join(contact_links)
    row["Tagline"] = tagline
    row["Description"] = description

    slug = _fallback_slug(brand)
    # Check if exists using string text to avoid sqlmodel deprecation warnings
    existing = await session.execute(
        text("SELECT id FROM vendor WHERE name = :name LIMIT 1"),
        {"name": brand}
    )
    vendor_record = existing.first()
    
    profile_text = f"{brand}. {tagline or ''} {description or ''} {seo_summary or ''}"
    embedding = await generate_embedding(profile_text)
    
    seo_content = {
        "summary": seo_summary,
        "services_list": extracted.get("services_list", []),
        "features_matrix": [],
        "pricing_model": "CPG Retail",
        "pros": [],
        "cons": []
    }
    schema_markup = {
        "@context": "https://schema.org",
        "@type": "Brand",
        "name": brand,
        "url": website,
        "description": seo_summary
    }

    if vendor_record:
        await session.execute(
            text("""
                UPDATE vendor
                SET website = :website,
                    tagline = :tagline,
                    description = :description,
                    profile_text = :profile_text,
                    seo_content = CAST(:seo_content AS jsonb),
                    schema_markup = CAST(:schema_markup AS jsonb),
                    embedding = CAST(:embedding AS vector),
                    embedding_model = :embedding_model,
                    updated_at = :now
                WHERE id = :id
            """),
            {
                "id": vendor_record.id,
                "website": website,
                "tagline": tagline,
                "description": description,
                "profile_text": profile_text,
                "seo_content": json.dumps(seo_content),
                "schema_markup": json.dumps(schema_markup),
                "embedding": str(embedding) if embedding else None,
                "embedding_model": EMBEDDING_MODEL if embedding else None,
                "now": datetime.utcnow()
            }
        )
    else:
        slug_check = await session.execute(
            text("SELECT id FROM vendor WHERE slug = :slug LIMIT 1"),
            {"slug": slug}
        )
        if slug_check.first():
            slug = f"{slug}-{int(datetime.utcnow().timestamp())}"
            
        await session.execute(
            text("""
                INSERT INTO vendor (
                    name, category, website, tagline, description, profile_text, 
                    seo_content, schema_markup, status, is_verified, tier_affinity,
                    slug, embedding, embedding_model, created_at, updated_at
                ) VALUES (
                    :name, :category, :website, :tagline, :description, :profile_text,
                    CAST(:seo_content AS jsonb), CAST(:schema_markup AS jsonb), :status, :is_verified, :tier_affinity,
                    :slug, CAST(:embedding AS vector), :embedding_model, :now, :now
                )
            """),
            {
                "name": brand,
                "category": row.get("Bucket", "Snack / Grocery"),
                "website": website,
                "tagline": tagline,
                "description": description,
                "profile_text": profile_text,
                "seo_content": json.dumps(seo_content),
                "schema_markup": json.dumps(schema_markup),
                "status": "unverified",
                "is_verified": False,
                "tier_affinity": "commodity",
                "slug": slug,
                "embedding": str(embedding) if embedding else None,
                "embedding_model": EMBEDDING_MODEL if embedding else None,
                "now": datetime.utcnow()
            }
        )
    
    await session.commit()
    return row

async def main():
    if not CSV_INPUT.exists():
        logger.error(f"Input CSV not found at {CSV_INPUT}")
        return

    processed_brands = set()
    fieldnames = []
    if CSV_OUTPUT.exists():
        with open(CSV_OUTPUT, "r", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            fieldnames = reader.fieldnames
            for r in reader:
                if r.get("Website") or r.get("Tagline") or r.get("Contact Names"):
                    processed_brands.add(r["Brand"])

    rows = []
    with open(CSV_INPUT, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        if not fieldnames:
            fieldnames = list(reader.fieldnames) + ["Website", "Contact Names", "Contact Titles", "Contact Links", "Tagline", "Description"]
            with open(CSV_OUTPUT, "w", encoding="utf-8", newline="") as out_f:
                writer = csv.DictWriter(out_f, fieldnames=fieldnames)
                writer.writeheader()
        
        for r in reader:
            rows.append(r)
            
    async_session_factory = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)
    
    total = len(rows)
    print("=====================================================")
    print(f"🚀 Starting CPG Outreach Enrichment ({total} brands)")
    print(f"   Resume state: Found {len(processed_brands)} already processed.")
    print("=====================================================\n")
    
    async with async_session_factory() as session:
        for i, row in enumerate(rows):
            brand = row["Brand"]
            percent = int(((i + 1) / total) * 100)
            
            if brand in processed_brands:
                # To reduce noise, we don't print "skipping" for every single one
                if (i+1) % 10 == 0:
                    logger.info(f"[{i+1}/{total}] ({percent}%) ⏩ Skipped up to {brand} (Already Processed)")
                continue
                
            logger.info(f"[{i+1}/{total}] ({percent}%) 🔍 Researching {brand}...")
            enriched_row = await process_brand(session, row)
            
            with open(CSV_OUTPUT, "a", encoding="utf-8", newline="") as out_f:
                writer = csv.DictWriter(out_f, fieldnames=fieldnames)
                writer.writerow(enriched_row)
            
            processed_brands.add(brand)
            logger.info("") # Empty line for readability

    print("\n=====================================================")
    print(f"✅ Finished processing {total} brands!")
    print(f"📂 Output saved to {CSV_OUTPUT}")
    print("=====================================================")

if __name__ == "__main__":
    import warnings
    from sqlalchemy import exc as sa_exc
    # Suppress deprecation warnings from duckduckgo and sqlalchemy for cleaner output
    warnings.filterwarnings("ignore", category=RuntimeWarning)
    warnings.filterwarnings("ignore", category=sa_exc.SAWarning)
    warnings.filterwarnings("ignore", module="sqlalchemy")
    
    # Hide noisy HTTPX/OpenAI logging
    logging.getLogger("httpx").setLevel(logging.WARNING)
    logging.getLogger("httpcore").setLevel(logging.WARNING)
    
    asyncio.run(main())
