"""
Static configuration for vendor discovery pipeline.
Extracted from discover_vendors.py — search queries by category and skip domains.
"""
from typing import Dict, List

# Domains to skip — aggregators, directories, social media
SKIP_DOMAINS = {
    "google.com", "www.google.com", "maps.google.com",
    "yelp.com", "www.yelp.com",
    "facebook.com", "www.facebook.com", "m.facebook.com",
    "linkedin.com", "www.linkedin.com",
    "instagram.com", "www.instagram.com",
    "twitter.com", "www.twitter.com", "x.com",
    "youtube.com", "www.youtube.com",
    "pinterest.com", "www.pinterest.com",
    "tiktok.com", "www.tiktok.com",
    "reddit.com", "www.reddit.com",
    "wikipedia.org", "en.wikipedia.org",
    "amazon.com", "www.amazon.com",
    "ebay.com", "www.ebay.com",
    "etsy.com", "www.etsy.com",
    "walmart.com", "www.walmart.com",
    "target.com", "www.target.com",
    "bbb.org", "www.bbb.org",
    "glassdoor.com", "www.glassdoor.com",
    "indeed.com", "www.indeed.com",
    "crunchbase.com", "www.crunchbase.com",
    "angi.com", "www.angi.com", "angieslist.com",
    "thumbtack.com", "www.thumbtack.com",
    "homeadvisor.com", "www.homeadvisor.com",
    "houzz.com", "www.houzz.com",
    "tripadvisor.com", "www.tripadvisor.com",
    "trustpilot.com", "www.trustpilot.com",
    "buildzoom.com", "www.buildzoom.com",
    "manta.com", "www.manta.com",
    "yellowpages.com", "www.yellowpages.com",
    "mapquest.com", "www.mapquest.com",
    "apple.com", "maps.apple.com",
    "nextdoor.com", "www.nextdoor.com",
}

# Search queries by category — each category has multiple queries to cast a wide net
CATEGORY_QUERIES: Dict[str, List[str]] = {
    "luxury_villas": [
        "luxury villa rental company",
        "luxury vacation home rental service",
        "private villa concierge service",
        "high end villa rental caribbean",
        "luxury villa rental europe mediterranean",
        "exclusive vacation rental company",
        "luxury ski chalet rental company",
        "private island rental service",
    ],
    "plastic_surgery": [
        "top plastic surgeon Beverly Hills",
        "best plastic surgeon New York City",
        "elite cosmetic surgeon Miami",
        "top rhinoplasty surgeon USA",
        "best facelift surgeon",
        "top body contouring surgeon",
        "celebrity plastic surgeon",
        "best plastic surgeon Nashville",
        "top plastic surgeon Dallas Houston",
        "best plastic surgeon Chicago",
    ],
    "luxury_cosmetics": [
        "luxury skincare brand",
        "high end cosmetics company",
        "premium anti-aging skincare brand",
        "luxury beauty brand",
        "exclusive skincare line",
        "prestige cosmetics brand",
        "luxury fragrance house",
        "high end makeup brand",
    ],
    "yacht_charter": [
        "luxury yacht charter company",
        "superyacht charter broker",
        "private yacht rental Mediterranean",
        "luxury catamaran charter Caribbean",
        "motor yacht charter company",
        "sailing yacht charter luxury",
        "yacht charter broker Florida",
        "luxury boat charter company",
    ],
    "private_aviation": [
        "private jet charter company",
        "fractional jet ownership",
        "private aviation membership",
        "jet card program",
        "private jet broker",
        "business aviation charter",
        "helicopter charter luxury",
        "private aircraft management company",
    ],
    "fine_jewelry": [
        "luxury jewelry designer",
        "high end custom jeweler",
        "bespoke diamond jeweler",
        "luxury watch dealer authorized",
        "fine jewelry brand",
        "estate jewelry dealer luxury",
        "custom engagement ring designer",
        "luxury jewelry store",
    ],
    "concierge_medicine": [
        "concierge medicine practice",
        "direct primary care luxury",
        "executive health program",
        "private physician practice",
        "VIP medical concierge",
        "longevity medicine clinic",
        "anti-aging medicine doctor",
        "functional medicine luxury practice",
    ],
    "luxury_real_estate": [
        "luxury real estate brokerage",
        "high end real estate agent",
        "luxury property management company",
        "mansion real estate broker",
        "waterfront luxury real estate",
        "luxury condo developer",
        "resort real estate developer",
        "luxury ranch real estate",
    ],
    "fine_art": [
        "fine art gallery contemporary",
        "art advisory firm",
        "luxury art dealer",
        "art collection management",
        "fine art auction house",
        "sculpture gallery luxury",
        "art investment advisory",
        "private art dealer",
    ],
    "luxury_automotive": [
        "exotic car dealer",
        "luxury car dealership",
        "supercar broker",
        "classic car dealer luxury",
        "luxury car rental company",
        "exotic car experience company",
        "armored vehicle luxury",
        "luxury electric vehicle dealer",
    ],
    "executive_protection": [
        "executive protection company",
        "celebrity bodyguard service",
        "VIP security firm",
        "close protection service",
        "luxury security company",
        "residential security company",
        "cybersecurity luxury family office",
        "threat assessment company",
    ],
    "luxury_events": [
        "luxury event planner",
        "high end wedding planner",
        "celebrity event planner",
        "luxury catering company",
        "private chef hire luxury",
        "luxury tent rental company",
        "exclusive venue rental",
        "luxury floral designer",
    ],
    "luxury_travel": [
        "luxury travel advisor",
        "bespoke travel company",
        "luxury safari operator",
        "expedition cruise company luxury",
        "luxury train journey company",
        "luxury wellness retreat",
        "adventure travel luxury",
        "luxury honeymoon planner",
    ],
    "home_services_luxury": [
        "luxury interior designer",
        "high end landscape architect",
        "luxury pool builder",
        "custom home builder luxury",
        "smart home installation company",
        "luxury closet designer",
        "wine cellar builder luxury",
        "luxury home theater installer",
    ],
    "wealth_management": [
        "family office advisory",
        "wealth management firm UHNW",
        "private banking services",
        "luxury financial advisor",
        "art and collectibles insurance",
        "luxury asset management",
        "estate planning attorney luxury",
        "trust and estate advisor",
    ],
}
