import asyncio
import json
import httpx
import os
import re
from typing import Optional, Dict
from duckduckgo_search import DDGS

from dotenv import load_dotenv
from pathlib import Path

load_dotenv(Path(__file__).parent.parent / ".env")

OLLAMA_API_URL = "http://localhost:11434/api/chat"
OLLAMA_MODEL = "gpt-oss:20b"
OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")

BRAND = "Magic Spoon"
BUYER_TITLES = "VP of Growth, Director of Shopper Marketing, VP Ecommerce, Performance Marketing Lead"

EXTRACT_PROMPT = """You are an expert B2B lead generator and data enricher. 
Research the CPG brand: "{brand}".

I have searched the web for you. Here is the context about the brand and people working there:
{search_context}

Your goal is to extract their company details and specific key personnel from the provided text.
Find the names, titles, and (if available) emails or LinkedIn URLs of people currently working at {brand} with any of these titles (or similar): {buyer_titles}.

You must output ONLY valid JSON format. Do NOT use tool calls. Do not include your thinking.
Fill in ALL the fields with the information you found in the context. Do not leave them empty if the information is available.
Required JSON Structure:
{{
    "website": "https://...",
    "tagline": "Short 1-sentence tagline",
    "description": "Detailed description of the company and their main products.",
    "seo_summary": "High-density 2-3 sentence summary of their core offerings.",
    "services_list": ["Product 1", "Product 2"],
    "contacts": [
        {{
            "name": "Jane Doe",
            "title": "VP of Growth",
            "email_or_linkedin": "jane@example.com or https://linkedin.com/in/..."
        }}
    ]
}}
"""

def perform_search(query: str) -> str:
    try:
        # Require 'cereal' or 'brand' to get better results for Magic Spoon
        results = DDGS().text(query, max_results=5)
        context = []
        for r in results:
            context.append(f"Title: {r.get('title')}\nURL: {r.get('href')}\nSnippet: {r.get('body')}\n")
        return "\n".join(context)
    except Exception as e:
        print(f"Search failed for '{query}': {e}")
        return ""

async def repair_json_with_openrouter(raw_text: str, context: str) -> Optional[Dict]:
    prompt = f"""You are a JSON repair and data extraction bot. 
The following text was generated by a weaker model trying to extract company info from search results.
It either produced invalid JSON, or it missed the details and returned empty fields.

Your job is to fix it. Use the provided Search Context to properly fill out the JSON.
Return ONLY valid JSON matching this schema. Do not include markdown fences.

Schema:
{{
    "website": "string",
    "tagline": "string",
    "description": "string",
    "seo_summary": "string",
    "services_list": ["string"],
    "contacts": [
        {{"name": "string", "title": "string", "email_or_linkedin": "string"}}
    ]
}}

Weak Model Output:
{raw_text}

Search Context:
{context}
"""
    try:
        async with httpx.AsyncClient(timeout=60) as client:
            resp = await client.post(
                "https://openrouter.ai/api/v1/chat/completions",
                headers={
                    "Authorization": f"Bearer {OPENROUTER_API_KEY}",
                    "Content-Type": "application/json",
                },
                json={
                    "model": "google/gemini-3-flash-preview",
                    "messages": [{"role": "user", "content": prompt}],
                    "temperature": 0.1
                }
            )
            resp.raise_for_status()
            content = resp.json()["choices"][0]["message"]["content"]
            content = content.strip()
            if content.startswith("```"):
                content = re.sub(r"^```(?:json)?\n?", "", content)
                content = re.sub(r"\n?```$", "", content)
            return json.loads(content)
    except Exception as e:
        print("Gemini JSON repair failed:", e)
        return None

async def test():
    print(f"Searching web for {BRAND}...")
    company_search = perform_search(f'"{BRAND}" CPG cereal')
    people_search = perform_search(f'"{BRAND}" ("VP of Growth" OR "Shopper Marketing" OR "VP Ecommerce") site:linkedin.com/in')
    
    context = f"--- COMPANY INFO ---\n{company_search}\n\n--- KEY PERSONNEL ---\n{people_search}"
    print("Web search complete. Context size:", len(context))
    print("--- CONTEXT PREVIEW ---")
    print(context[:1000] + "...\n-----------------------\n")
    
    prompt = EXTRACT_PROMPT.format(brand=BRAND, buyer_titles=BUYER_TITLES, search_context=context)
    
    print(f"Asking {OLLAMA_MODEL}...")
    raw_content = ""
    try:
        async with httpx.AsyncClient(timeout=300) as client:
            resp = await client.post(
                OLLAMA_API_URL,
                json={
                    "model": OLLAMA_MODEL,
                    "messages": [{"role": "user", "content": prompt}],
                    "stream": False,
                    "options": {
                        "temperature": 0.1,
                        "num_predict": 1000
                    }
                },
            )
            data = resp.json()
            msg = data.get("message", {})
            raw_content = msg.get("content", "")
    except Exception as e:
        print("Ollama call failed:", e)
        return

    print("\n--- RAW LLM OUTPUT ---")
    print(raw_content)
    print("----------------------\n")
    
    needs_repair = False
    try:
        cleaned = raw_content.strip()
        if cleaned.startswith("```"):
            cleaned = re.sub(r"^```(?:json)?\n?", "", cleaned)
            cleaned = re.sub(r"\n?```$", "", cleaned)
        parsed = json.loads(cleaned)
        
        # Check if the model hallucinated empty fields
        if not parsed.get("website") and not parsed.get("tagline") and not parsed.get("contacts"):
            print("❌ Ollama parsed successfully but returned empty fields.")
            needs_repair = True
        else:
            print("✅ Successfully parsed JSON directly from Ollama:")
            print(json.dumps(parsed, indent=2))
            
    except json.JSONDecodeError as e:
        print("❌ Failed to parse JSON from Ollama:", e)
        needs_repair = True
        
    if needs_repair:
        print("🔧 Sending to Gemini via OpenRouter for repair & extraction...")
        parsed = await repair_json_with_openrouter(raw_content, context)
        if parsed:
            print("✅ Successfully repaired & extracted JSON via Gemini:")
            print(json.dumps(parsed, indent=2))
        else:
            print("❌ Gemini failed to repair JSON.")

if __name__ == "__main__":
    asyncio.run(test())
