#!/usr/bin/env bash
# Setup Framework Structure - Git Exclude Work Artifacts
# This separates framework (in git) from work artifacts (per-developer)

set -euo pipefail

GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${BLUE}═══════════════════════════════════════════════════${NC}"
echo -e "${BLUE}  Framework Structure Setup${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════${NC}"
echo ""

PROJECT_DIR="${1:-.}"

if [ ! -d "$PROJECT_DIR" ]; then
  echo -e "${YELLOW}Error: Directory doesn't exist: $PROJECT_DIR${NC}"
  exit 1
fi

cd "$PROJECT_DIR"

echo -e "${BLUE}Setting up:${NC} $(pwd)"
echo ""

if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  echo -e "${YELLOW}Error: Not inside a git repository${NC}"
  exit 1
fi

EXCLUDE_FILE=".git/info/exclude"
mkdir -p .git/info

if [ ! -f "$EXCLUDE_FILE" ]; then
  touch "$EXCLUDE_FILE"
  echo -e "${GREEN}✓ Created $EXCLUDE_FILE${NC}"
fi

append_unique() {
  local pattern="$1"
  local label="$2"
  if grep -Fxq "$pattern" "$EXCLUDE_FILE" 2>/dev/null; then
    echo -e "${BLUE}ℹ️  $label already present in $EXCLUDE_FILE${NC}"
  else
    printf '%s\n' "$pattern" >> "$EXCLUDE_FILE"
    echo -e "${GREEN}✓ Added $label to $EXCLUDE_FILE${NC}"
  fi
}

echo '' >> "$EXCLUDE_FILE"
append_unique "# CFOI work artifacts (per-developer, local only)" "section header"
append_unique ".cfoi/" ".cfoi/"
append_unique "# Optional local AI checklists" "optional checklists header"
append_unique "checklist-*.md" "checklist pattern"
append_unique "# Optional personal notes" "optional notes header"
append_unique "*-notes.md" "notes pattern"
append_unique "*-scratch.md" "scratch pattern"
append_unique "# Windsurf transient artifacts" "windsurf header"
append_unique ".swarm/" ".swarm/"
append_unique ".windsurf/cache/" ".windsurf/cache/"
append_unique ".checkpoint" ".checkpoint"

# Remove .cfoi from git if it was tracked
if git ls-files --error-unmatch .cfoi/ >/dev/null 2>&1; then
  git rm -r --cached .cfoi/
  echo -e "${GREEN}✓ Removed .cfoi/ from git (cached)${NC}"
  echo -e "${YELLOW}  Remember to commit this change!${NC}"
else
  echo -e "${BLUE}ℹ️  .cfoi/ not tracked in git (good)${NC}"
fi

# Create local CFOI directory
mkdir -p .cfoi/branches
echo -e "${GREEN}✓ Created .cfoi/branches/${NC}"

# Add README to .cfoi
cat > .cfoi/README.md << 'EOF'
# CFOI Work Artifacts

This directory contains **branch-specific planning artifacts** generated by the
Windsurf workflows. Contents stay out of git so every developer can iterate
privately.

## Workflow Outputs

- `/plan` → `.cfoi/branches/<branch>/plan.md`
- `/task` → `.cfoi/branches/<branch>/tasks.md`
- `/implement` → `.cfoi/branches/<branch>/proof/<task-id>/...`

Store manual verification notes, screenshots, and coverage logs under
`proof/`. These files back up the evidence the hooks look for.

## Tracking vs. Non-Tracking

| Location | Tracked? | Purpose |
|----------|----------|---------|
| `.cfoi/` | ❌ No | Personal plans, notes, proofs |
| `.windsurf/` | ✅ Yes | Shared workflows & constitution |
| `tools/` | ✅ Yes | Project scripts |
| `src/` | ✅ Yes | Application code |
| `tests/` | ✅ Yes | Automated tests |

Keep experimenting freely — **we review code, not your private notes.** 🚀
EOF
echo -e "${GREEN}✓ Created .cfoi/README.md${NC}"

echo ""
echo -e "${BLUE}═══════════════════════════════════════════════════${NC}"
echo -e "${GREEN}✨ Setup Complete!${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════${NC}"
echo ""
echo -e "${BLUE}Structure:${NC}"
echo ""
echo "  ✅ In Git (Shared Framework):"
echo "     .windsurf/      - Workflows & constitution"
echo "     tools/          - Scripts & templates"  
echo "     *.md            - Documentation"
echo ""
echo "  ❌ Not in Git (Private Work):"
echo "     .cfoi/          - Your planning artifacts"
echo ""
echo -e "${YELLOW}Next Steps:${NC}"
echo ""
echo "  1. Start planning (your notes stay local):"
echo -e "     ${BLUE}/plan${NC} or ${BLUE}/task${NC} in Windsurf"
echo ""
echo -e "${GREEN}Framework is shared, planning is private! 🎉${NC}"
echo ""
